export const commands: Chat.ChatCommands = {
	ctm(target, room, user, connection) {
		if (Monitor.countPrepBattle(connection.ip, connection)) {
			return;
		}
		if (!target) return this.errorReply(this.tr`Provide a valid slot.`);
		const slot = Number(target);
		if (isNaN(slot)) return this.errorReply(this.tr`Provide a valid slot.`);
		const format = Dex.formats.get('gen9balancedcreatemons');
		const newTeam = user.battleSettings.team.split(']')[slot];

		return TeamValidatorAsync.get(format.id).validateTeam(newTeam).then(result => {
			connection.popup(`${result.slice(1).replace(/\n/g, '\n- ')}`);
		});
	},
	ctmhelp: [`/ctm [slot] - Validates your current Createmons set (set with /utm).`],

	crtm: 'createmons',
	createmons(target, room, user, connection) {
		if (!target) return this.parse('/help crtm');
		if (target === 'formula') {
			this.sendReplyBox(
				`Createmons 分数计算方法：<br />` + 
				`&bullet;首先计算出以下几项：<br />` + 
				`BST：种族和 <br />` + 
				`SD：种族值标准差（种族分配得越极端这项越大）<br />` + 
				`T：属性分。如果是双属性则为两种属性的分数之和；如果是单属性则为属性分数乘以 1.5 <br />` + 
				`A：特性分 <br />` + 
				`M：招式分。等于各招式分数之和，空白招式计 0.5 分 <br />` + 
				`&bullet;总分 = (BST - 450) * (SD + 100) * T * A * M / 100 <br />` + 
				`如果 BST 小于 500，则上面式子中第一项固定为 50。`
			);
			return;
		}
		const typeToPoint: {[k: string]: number} = {
			Bug: 0.5,
			Dark: 2,
			Dragon: 2,
			Electric: 2,
			Fairy: 3,
			Fighting: 1.5,
			Fire: 2.5,
			Flying: 2,
			Ghost: 2.5,
			Grass: 1,
			Ground: 2,
			Ice: 1,
			Normal: 2.5,
			Poison: 1,
			Psychic: 1,
			Rock: 1,
			Steel: 3,
			Water: 2.5,
		};
		const abilityToPoint: {[k: string]: number} = {
			adaptability: 3,
			aerilate: 4,
			armortail: 2.5,
			asoneglastrier: 1.5,
			asonespectrier: 1.5,
			beadsofruin: 3.5,
			beastboost: 1.5,
			chillingneigh: 1.5,
			chlorophyll: 2,
			comatose: 1.5,
			contrary: 5,
			corrosion: 2,
			darkaura: 1.5,
			dazzling: 2.5,
			defeatist: 0.5,
			desolateland: 3.5,
			disguise: 5,
			download: 2,
			dragonsmaw: 3,
			drizzle: 4,
			drought: 4,
			dryskin: 2,
			eartheater: 2,
			electricsurge: 3,
			fairyaura: 1.5,
			filter: 1.5,
			flareboost: 2,
			flashfire: 2,
			fluffy: 3,
			furcoat: 4,
			galewings: 1.5,
			galvanize: 3,
			goodasgold: 3.5,
			gorillatactics: 4.5,
			grassysurge: 1.5,
			grimneigh: 1.5,
			gulpmissile: 5,
			guts: 2,
			hustle: 2,
			hadronengine: 3.5,
			iceface: 2,
			icescales: 4,
			illusion: 5,
			imposter: 4,
			intimidate: 2.5,
			intrepidsword: 1.5,
			levitate: 1.5,
			libero: 3,
			lightningrod: 2.5,
			magicbounce: 3,
			magicguard: 3.5,
			magnetpull: 5,
			megalauncher: 2,
			mistysurge: 2,
			moldbreaker: 3,
			moody: 5,
			motordrive: 2,
			moxie: 1.5,
			multiscale: 2,
			neuroforce: 1.5,
			noguard: 4,
			normalize: 4,
			orichalcumpulse: 4.5,
			parentalbond: 5,
			pixilate: 4,
			poisonheal: 4,
			prankster: 3.5,
			pressure: 1.5,
			primordialsea: 3.5,
			prismarmor: 1.5,
			protean: 3,
			protosynthesis: 2,
			psychicsurge: 3.5,
			punkrock: 1.5,
			purifyingsalt: 1.5,
			quarkdrive: 2,
			queenlymajesty: 2.5,
			quickdraw: 1.5,
			refrigerate: 4,
			regenerator: 4,
			rockhead: 1.5,
			rockpayload: 2,
			sandrush: 1.5,
			sandstream: 2.5,
			sapsipper: 2,
			scrappy: 1.5,
			serenegrace: 1.5,
			shadowshield: 2,
			sharpness: 1.5,
			sheerforce: 2.5,
			shielddust: 1.5,
			simple: 2.5,
			skilllink: 1.5,
			slowstart: 0.5,
			slushrush: 1.5,
			sniper: 2.5,
			snowwarning: 2,
			solarpower: 1.5,
			solidrock: 1.5,
			soulheart: 1.5,
			soundproof: 2,
			speedboost: 2.5,
			stakeout: 5,
			stamina: 1.5,
			steelworker: 2.5,
			steelyspitit: 2.5,
			stormdrain: 2,
			strongjaw: 2,
			sturdy: 1.5,
			surgesurfer: 2,
			swiftswim: 2.5,
			swordofruin: 3.5,
			tabletofruin: 2,
			technician: 2,
			teravolt: 3,
			thickfat: 1.5,
			tintedlens: 3,
			toughclaws: 3,
			toxicboost: 1.5,
			transistor: 2.5,
			triage: 3.5,
			truant: 0.5,
			turboblaze: 3,
			unaware: 3,
			unburden: 2.5,
			unseenfist: 1.5,
			vesselofruin: 2,
			voltabsorb: 2,
			waterabsorb: 2,
			waterbubble: 5,
			wellbakedbody: 2.5,
		};
		const moveToPoint: {[k: string]: number} = {
			accelerock: 1,
			acidarmor: 1,
			acupressure: 1,
			aeroblast: 1,
			anchorshot: 1.5,
			appleacid: 1,
			aquajet: 1,
			armorcannon: 2,
			aromatherapy: 1.5,
			assist: 1,
			astralbarrage: 2,
			aurasphere: 1,
			auroraveil: 1.5,
			axekick: 2,
			baddybad: 2,
			banefulbunker: 1,
			barrier: 1,
			batonpass: 1.5,
			beakblast: 1.5,
			behemothbash: 1.5,
			behemothblade: 1.5,
			bellydrum: 2.5,
			bitterblade: 1.5,
			blastburn: 1.5,
			blazingtorque: 1,
			bleakwindstorm: 1,
			blizzard: 1.5,
			block: 1,
			blueflare: 2,
			bodypress: 1.5,
			boltbeak: 2.5,
			boltstrike: 2,
			bonemerang: 1,
			boomburst: 2,
			bravebird: 1.5,
			bulkup: 1.5,
			burnup: 1.5,
			buzzybuzz: 2.5,
			calmmind: 1.5,
			ceaselessedge: 2,
			chatter: 2,
			chillyreception: 1.5,
			chloroblast: 2,
			circlethrow: 1,
			clangingscales: 1.5,
			clangoroussoul: 1.5,
			closecombat: 2,
			coil: 1.5,
			collisioncourse: 2,
			combattorque: 2,
			comeuppance: 1,
			copycat: 1,
			coreenforcer: 2,
			corrosivegas: 1.5,
			cosmicpower: 1.5,
			cottonguard: 1.5,
			counter: 1,
			courtchange: 2,
			crabhammer: 1,
			curse: 1,
			darkvoid: 2,
			defendorder: 1.5,
			destinybond: 2,
			diamondstorm: 1.5,
			disable: 1,
			direclaw: 1.5,
			doomdesire: 2,
			doubleedge: 1.5,
			doubleshock: 1.5,
			dracometeor: 2,
			dragonascent: 2,
			dragondance: 2,
			dragondarts: 1.5,
			dragonenergy: 2,
			dragontail: 1,
			drainingkiss: 1.5,
			drainpunch: 1.5,
			dynamaxcannon: 1.5,
			dynamicpunch: 1.5,
			earthpower: 1.5,
			earthquake: 1.5,
			electrify: 1.5,
			electrodrift: 2,
			encore: 1.5,
			endeavor: 2,
			entrainment: 1.5,
			eruption: 2,
			eternabeam: 1.5,
			expandingforce: 2,
			explosion: 2.5,
			extremespeed: 2,
			facade: 2,
			fairylock: 1,
			fakeout: 1.5,
			feint: 1,
			fierydance: 1,
			filletaway: 2,
			finalgambit: 2.5,
			fireblast: 1.5,
			firelash: 1.5,
			firespin: 1,
			firstimpression: 1.5,
			fishiousrend: 2.5,
			flail: 1,
			flareblitz: 1.5,
			fleurcannon: 2,
			flipturn: 1.5,
			flowertrick: 1.5,
			focusblast: 2,
			freezedry: 1,
			freezeshock: 1,
			freezyfrost: 1.5,
			frenzyplant: 1.5,
			frostbreath: 1.5,
			frustration: 1.5,
			gastroacid: 1,
			geomancy: 1.5,
			gigaimpact: 1.5,
			gigatonhammer: 2,
			glaciallance: 2,
			glaiverush: 2,
			glare: 1.5,
			glitzyglow: 2,
			grassknot: 1.5,
			grasswhistle: 2,
			gravapple: 1,
			growth: 1.5,
			gunkshot: 2,
			gyroball: 1,
			haze: 1.5,
			hammerarm: 1,
			headcharge: 2,
			headlongrush: 2,
			headsmash: 2,
			healbell: 1.5,
			healblock: 1,
			healingwish: 1.5,					
			healorder: 2,
			heartswap: 1,
			hex: 1,
			highjumpkick: 2,
			honeclaws: 1,
			howl: 1,
			hurricane: 1.5,
			hydrocannon: 1.5,
			hydropump: 1.5,
			hyperbeam: 1.5,
			hyperdrill: 1.5,
			hypnosis: 2,
			iceburn: 1.5,
			icehammer: 1,
			iceshard: 1,
			imprison: 1.5,
			infernalparade: 1,
			inferno: 1.5,
			infestation: 1.5,
			irondefense: 1,
			jawlock: 1.5,
			jetpunch: 1,
			judgment: 2,
			junglehealing: 1,
			kingsshield: 1,
			knockoff: 1.5,
			lastresort: 2,
			lastrespects: 2.5,
			lavaplume: 1.5,
			leafstorm: 2,
			leechseed: 1.5,
			lightofruin: 2,
			lightscreen: 1.5,
			lovelykiss: 2,
			lowkick: 1.5,
			luminacrash: 2,
			lunarblessing: 1,
			lunardance: 1.5,
			machpunch: 1,
			magicaltorque: 2,
			magmastorm: 1.5,
			makeitrain: 2,
			meanlook: 1,
			meditate: 1,
			megahorn: 1.5,
			megakick: 1.5,
			memento: 1.5,
			metalburst: 1,
			meteorassault: 1.5,
			meteorbeam: 1.5,
			milkdrink: 1.5,
			mindblown: 2,
			mirrorcoat: 1,
			mirrormove: 1,
			mistyexplosion: 1.5,
			moonblast: 1.5,
			moongeistbeam: 2,
			moonlight: 1.5,
			morningsun: 1.5,
			mortalspin: 1.5,
			mountaingale: 1.5,
			multiattack: 2,
			nastyplot: 1.5,
			naturepower: 1,
			naturesmadness: 1.5,
			noretreat: 2,
			noxioustorque: 1.5,
			nuzzle: 1.5,
			oblivionwing: 1.5,
			obstruct: 1,
			octolock: 2.5,
			originpulse: 1.5,
			outrage: 1.5,
			overheat: 2,
			partingshot: 1.5,
			perishsong: 1.5,
			petaldance: 1.5,
			photongeyser: 2,
			pikapapow: 1.5,
			plasmafists: 1.5,
			poisonfang: 1.5,
			poltergeist: 1.5,
			populationbomb: 2,
			powertrick: 1,
			powertrip: 1.5,
			poweruppunch: 1,
			powerwhip: 2,
			precipiceblades: 2,
			prismaticlaser: 1.5,
			protect: 1,
			psychup: 1,
			psychoboost: 2,
			psychoshift: 1.5,
			psyshieldbash: 1,
			psystrike: 1.5,
			purify: 1,
			pursuit: 1.5,
			pyroball: 2,
			quickattack: 1,
			quiverdance: 2,
			ragingfury: 1.5,
			rapidspin: 1,
			recover: 1.5,
			recycle: 1,
			reflect: 1.5,
			relicsong: 1.5,
			return: 1.5,
			revelationdance: 1.5,
			reversal: 1,
			risingvoltage: 2,
			roar: 1,
			roaroftime: 1.5,
			rockwrecker: 1.5,
			roost: 1.5,
			ruination: 1.5,
			sacredfire: 1.5,
			saltcure: 1,
			sandsearstorm: 1.5,
			sandtomb: 1,
			sappyseed: 2,
			scald: 1.5,
			scorchingsands: 1.5,
			secretsword: 1.5,
			seedflare: 2,
			selfdestruct: 2.5,
			shadowforce: 2,
			shadowsneak: 1,
			sharpen: 1,
			shellsmash: 2.5,
			shelter: 1,
			shiftgear: 2,
			shoreup: 1.5,
			silktrap: 1,
			sing: 2,
			sizzlyslide: 2.5,
			skillswap: 1.5,
			skyattack: 1.5,
			slackoff: 1.5,
			sleeppowder: 2,
			sleeptalk: 1.5,
			snaptrap: 1,
			softboiled: 1.5,
			solarbeam: 1.5,
			solarblade: 1.5,
			spacialrend: 1.5,
			sparklyswirl: 2.5,
			spectralthief: 1.5,
			spikes: 1.5,
			spikyshield: 1,
			spiritshackle: 1.5,
			spite: 1,
			splishysplash: 1.5,
			spore: 2.5,
			springtidestorm: 1.5,
			stealthrock: 1.5,
			steameruption: 2,
			steelbeam: 2,
			steelroller: 1.5,
			stickyweb: 2,
			stoneaxe: 2,
			storedpower: 1.5,
			stormthrow: 1.5,
			strengthsap: 1.5,
			substitute: 1.5,
			suckerpunch: 1.5,
			sunsteelstrike: 2,
			superfang: 1.5,
			superpower: 2,
			surgingstrikes: 1.5,
			switcheroo: 1.5,
			swordsdance: 1.5,
			synthesis: 1.5,
			tailglow: 2,
			tailwind: 1,
			taunt: 2,
			technoblast: 1.5,
			teleport: 1.5,
			thousandarrows: 2,
			thousandwaves: 1.5,
			thrash: 1.5,
			thunder: 1.5,
			thundercage: 2,
			thunderouskick: 2,
			thunderwave: 1,
			tidyup: 2,
			topsyturvy: 1.5,
			torchsong: 1.5,
			toxic: 1.5,
			toxicspikes: 1.5,
			toxicthread: 1,
			transform: 2.5,
			trick: 1.5,
			trickroom: 1.5,
			triplearrows: 1.5,
			tripleaxel: 1.5,
			uturn: 1.5,
			vacuumwave: 1,
			vcreate: 2.5,
			veeveevolley: 1.5,
			victorydance: 2,
			voltswitch: 1.5,
			volttackle: 1.5,
			watershuriken: 1.5,
			waterspout: 2,
			wavecrash: 1.5,
			whirlpool: 1,
			whirlwind: 1,
			wickedblow: 1.5,
			wickedtorque: 2,
			willowisp: 1.5,
			wish: 1,
			woodhammer: 1.5,
			workup: 1,
			worryseed: 1,
			yawn: 1.5,
			zapcannon: 2,
		};
		const type = Dex.types.get(target);
		const ability = Dex.abilities.get(target);
		const move = Dex.moves.get(target);
		if (type.exists) {
			this.sendReply(`${type.name}'s point is ${typeToPoint[type.name]}.`);
			return;
		}
		if (ability.exists) {
			this.sendReply(`${ability.name}'s point is ${abilityToPoint[ability.id] || 1}.`);
			return;
		}
		if (move.exists) {
			this.sendReply(`${move.name}'s point is ${moveToPoint[move.id] || 0.5}`);
			return;
		}
		this.errorReply(`Type/Ability/Move doesn't exist.`);
	},
	createmonshelp: [
		`/crtm or /createmons [type/ability/move] - See the point of that type/ability/move in Createmons.`, 
		`/crtm or /createmons formula - See the formula Createmons uses to calculate the point.`
	],
}